sb_user:
    resource: "@SBUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_registration_register:
    path:      /new
    defaults:  { _controller: FOSUserBundle:Registration:register }