login_check:
    path: /login_check

sb_default:
    path: /
    defaults: { _controller: 'SBUserBundle:Default:index' }

sb_user:
    type: rest
    resource: SB\UserBundle\Controller\UserController
