services:
    sb_api.event.jwt_created_listener:
        class: SB\UserBundle\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
    sb_api.event.jwt_decoded_listener:
        class: SB\UserBundle\EventListener\JWTDecodedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }
    sb_api.event.jwt_authenticated_listener:
        class: SB\UserBundle\EventListener\JWTResponseListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    app.form.registration:
        class: SB\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.handler.registration:
        class: SB\UserBundle\Form\Handler\RegistrationFormHandler
        arguments: ["@fos_user.registration.form", "@request", "@fos_user.user_manager", "@fos_user.mailer", "@fos_user.util.token_generator"]
        scope: request
        public: false